# -*- coding: utf-8 -*-
"""mr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vr4dCZf-hv1xeH88MUZOSKFIe6cf_L6k
"""

import streamlit as st
import pandas as pd
from datetime import datetime
import os

# =============================
# Configuración de la página
# =============================
st.set_page_config(
    page_title="Pedidos – Marisquería Ramírez",
    page_icon="🦐",
    layout="centered"
)

# =============================
# Encabezado
# =============================
st.title("🦐 Marisquería Ramírez")
st.subheader("Sistema de pedidos de insumos")

# Imagen local
st.image(
    "mr.jpeg",
    caption="Marisquería Ramírez",
    use_container_width=True,width=100
)

st.divider()

# =============================
# Catálogo de productos
# =============================
catalogo = [
    # -------- SAMS --------
    {"Familia": "SAMS", "Producto": "CLORO", "Especificación": "10 LITROS"},
    {"Familia": "SAMS", "Producto": "FABULOSO (LAVANDA)", "Especificación": "10 LITROS"},
    {"Familia": "SAMS", "Producto": "ARROZ VALLE VERDE", "Especificación": "5 PZAS. 1 KG"},
    {"Familia": "SAMS", "Producto": "FRIJO VALLE VERDE (FLOR DE MAYO)", "Especificación": "2.5 KG"},
    {"Familia": "SAMS", "Producto": "FRIJO VALLE VERDE (NEGRO)", "Especificación": "2.5 KG"},
    {"Familia": "SAMS", "Producto": "ACEITE 1-2-3", "Especificación": "PAQUETE 3 LITROS"},
    {"Familia": "SAMS", "Producto": "VALENTINA ROJA", "Especificación": "350 ML (6 PZAS)"},
    {"Familia": "SAMS", "Producto": "VALENTINA ROJA", "Especificación": "4 LITROS (1 PZA)"},

    # -------- MATERIA PRIMA --------
    {"Familia": "MATERIA PRIMA", "Producto": "CHAROLA 835", "Especificación": "FILETES"},
    {"Familia": "MATERIA PRIMA", "Producto": "CHAROLA 855", "Especificación": "PEDIDOS GRANDES"},
    {"Familia": "MATERIA PRIMA", "Producto": "CHAROLA 066", "Especificación": "PEDIDOS MEDIANOS"},
    {"Familia": "MATERIA PRIMA", "Producto": "BOLSA CHICA (1)", "Especificación": "PEDIDOS CHICOS"},
    {"Familia": "MATERIA PRIMA", "Producto": "BOLSA (2)", "Especificación": "PEDIDOS GRANDES"},

    # -------- SALSAS --------
    {"Familia": "SALSAS", "Producto": "VALENTINA NEGRA", "Especificación": "350 ML"},
    {"Familia": "SALSAS", "Producto": "VALENTINA AZUL", "Especificación": "350 ML"},
]

df = pd.DataFrame(catalogo)

# =============================
# Realizar pedido
# =============================
st.header("🛒 Realizar pedido")

pedido = []

for familia in df["Familia"].unique():
    st.subheader(f"📦 {familia}")
    productos = df[df["Familia"] == familia]

    for _, row in productos.iterrows():
        col1, col2 = st.columns([3, 1])

        with col1:
            st.write(f"**{row['Producto']}** – {row['Especificación']}")

        with col2:
            cantidad = st.number_input(
                "Cantidad",
                min_value=0,
                step=1,
                key=f"{row['Producto']}_{row['Especificación']}"
            )

        if cantidad > 0:
            pedido.append({
                "Familia": familia,
                "Producto": row["Producto"],
                "Especificación": row["Especificación"],
                "Cantidad": cantidad
            })

# =============================
# Resumen y guardado
# =============================
st.divider()
st.header("📋 Resumen del pedido")

if pedido:
    df_pedido = pd.DataFrame(pedido)
    st.dataframe(df_pedido, use_container_width=True)

    # Guardar CSV
    fecha = datetime.now().strftime("%Y%m%d_%H%M%S")
    nombre_archivo = f"pedido_marisqueria_{fecha}.csv"

    if st.button("💾 Guardar pedido en CSV"):
        df_pedido["Fecha"] = datetime.now().strftime("%Y-%m-%d")
        df_pedido["Hora"] = datetime.now().strftime("%H:%M:%S")

        df_pedido.to_csv(nombre_archivo, index=False, encoding="utf-8-sig")

        st.success(f"Pedido guardado correctamente como `{nombre_archivo}` ✅")

        # Descargar desde Streamlit
        with open(nombre_archivo, "rb") as file:
            st.download_button(
                label="⬇️ Descargar pedido",
                data=file,
                file_name=nombre_archivo,
                mime="text/csv"
            )

else:
    st.info("Aún no has agregado productos al pedido.")
